### ISSUE TITLE
ntuple(n::Integer,f::Function) is deprecated

### ISSUE THREAD

**Issue by hackjackhack** [JuliaLang/Options.jl#9]
Running on Julia Version 0.4.0-dev+5236 (Commit 01abdc3*), options.jl gives the following warning:

WARNING: ntuple(n::Integer,f::Function) is deprecated, use ntuple(f,n) instead.

**Comment by nalimilan** [comment]
Thanks for the report. This should be quite easy to fix, by simply swapping `n` and `f`. Would you prepare a pull request for this? You can even make the change online on GitHub. To find where the warning comes from, just have a look at the bracktrace.

**Comment by ivarne** [comment]
Was this fixed by https://github.com/JuliaLang/Options.jl/pull/11? 
Cc @lostanlen

**Comment by lostanlen** [comment]
Yes, since with #11 ```ntuple``` is no longer called in latest master. The issue can be closed.
